cisco:
  children:
    usa:
      hosts:
        R1:
          ansible_host: 10.0.0.21
        R2:
          ansible_host: 10.0.0.22
    eu:
      hosts:
        R3:
          ansible_host: 10.0.0.23
        R4:
          ansible_host: 10.0.0.24
