# cisco:
#   children:
#     usa:
#       hosts:
#         R1:
#           ansible_host: 10.0.0.21
#         R2:
#           ansible_host: 10.0.0.22
#     eu:
#       hosts:
#         R3:
#           ansible_host: 10.0.0.23
#         R4:
#           ansible_host: 10.0.0.24
# vyos:
#   hosts:
#     R5:
#       ansible_host: 10.0.0.25

# cisco:
#   hosts:
#     R1:
#       ansible_host: 10.0.0.21
#     R2:
#       ansible_host: 10.0.0.22

# vyos:
#   hosts:
#     R3:
#       ansible_host: 10.0.0.23
#     R4:
#       ansible_host: 10.0.0.24

# cisco:
#   hosts:
#     SW5:
#       ansible_host: 10.0.0.25
#     SW6:
#       ansible_host: 10.0.0.26

# vyos:
#   hosts:
#     R7: 
#       ansible_host: 10.0.0.27
#     R8:
#       ansible_host: 10.0.0.28

arista:
  hosts:
    SW1:
      ansible_host: 10.0.0.31

cisco:
  hosts:
    SW2:
      ansible_host: 10.0.0.32