---
- name: "Loop test"
  hosts: usa
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Gather Cisco Facts"
      cisco.ios.ios_facts:
        gather_subset: all

    - name: "Print Cisco Facts"
      ansible.builtin.debug:
        msg: "{{ ansible_net_hostname }} has an IP address {{ item }} configured."
      loop: "{{ ansible_net_all_ipv4_addresses }}"
