---
- name: "Register playbook"
  hosts: "R1"
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Push config"
      cisco.ios.ios_config:
        src: "ntp.j2"
      notify: ntp_handler_example
      register: ntp_results

  handlers:
    - name: "HANDLER 1 - This will check for NTP updates"
      listen: "ntp_handler_example"
      ansible.builtin.debug:
        msg: "{{ ntp_results }}"
