---
- name: "Filter Test"
  hosts: R1

  tasks:
    - name: "Testing some filter stuff"
      vars:
        usa_prefixes:
          - "192.168.0.0/24"
          - "10.0.0.0/30"
          - "1.1.1.1/32"
        eu_prefixes:
          - "192.168.0.0/24"
          - "10.0.0.0/30"
      ansible.builtin.debug:
        msg: "{{ usa_prefixes | symmetric_difference(eu_prefixes) }}"
