---
- name: Tagging Tasks
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Create User
      cisco.ios.ios_config:
        lines:
          - username emilia priv 15 secret user123
      register: user_output
      tags: create_user

    - ansible.builtin.debug: var=user_output
      tags: create_user

    - name: NTP Config
      cisco.ios.ios_config:
        lines:
          - ntp server 1.2.3.4
      register: ntp_output
      tags: ntp

    - ansible.builtin.debug: var=ntp_output
      tags: ntp
