---
- name: "Filter Test"
  hosts: R1

  tasks:
    - name: "IP address filter stuff"
      vars:
        myip:
          - "192.168.55.1"
          - "10.0.0.1"
          - "999.999.999.999"
          - "2001:db8:aaa:bbbb::1"
      ansible.builtin.debug:
        msg: "{{ myip | ansible.utils.ipaddr }}"
    
    - name: "IP address filter stuff"
      vars:
        myip: "192.168.0.1/24"
      ansible.builtin.debug:
        msg: "{{ myip | ansible.utils.ipaddr('address') }}"