---

- name: MY FIRST PLAYBOOK
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    - name: OSPF CONFIG
      cisco.ios.ios_config:
        lines:
          - router-id 2.2.2.2
        parents:
          - router ospf 19
      register: my_output
    - name: "Show OSPF Config Output"
      ansible.builtin.debug:
        var: my_output
