---
- name: "Playbook to validate devices"
  hosts: all
  connection: network_cli

  tasks:
    - name: "Task1 - use NAPALM validate"
      napalm_validate:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        validation_file: "NAPALM-Ansible-playbooks/{{ inventory_hostname }}-facts.yml"
      register: result
      ignore_errors: yes

    - name: "Task1 - Print the results"
      ansible.builtin.debug:
        var: result