---
- name: "Playbook to test NAPALM Ansible"
  hosts: all
  connection: network_cli

  tasks:
    - name: "Retrieve device facts via NAPALM"
      napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        filter: ["interfaces_counters", "mac_address_table"]
      register: result
    
    - name: Print Result
      ansible.builtin.debug:
        var: result.ansible_facts.napalm_mac_address_table[0].mac