---
- name: "Playbook to push templated EIGRP config to usa hosts"
  hosts: "usa"
  gather_facts: false
  connection: "network_cli"

  tasks:
    - name: "Push EIGRP Config"
      cisco.ios.ios_config:
        src: "eigrp_{{ eigrp.style }}.j2"
      register: "eigrp_debug"

    - name: "Print Debug"
      ansible.builtin.debug:
        var: "eigrp_debug"
