---
ospf:
  rid: "3.3.3.3"
  networks:
    - address: "10.0.20.0/30"
  area: "0"

bgp:
  asn: 3
  rid: "3.3.3.3"
  peers:
    - neighbor: "10.0.20.1"
      peer_type: "external"
      peer_asn: "2"
    - neighbor: "10.0.20.10"
      peer_type: "external"
      peer_asn: "4"

# bgp:
#   asn: "65001"
#   rid: "3.3.3.3"
#   peers:
#     - neighbor: "10.0.10.9"
#       peer_asn: "65001"

#     - neighbor: "10.0.10.13"
#       peer_asn: "65001"

#     - neighbor: "10.0.10.22"
#       peer_asn: "65001"
#   networks:
#     - network: "3.3.3.3"
#       mask: "255.255.255.255"
      